version: '{branch}-{build}'

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+[\w\-]*$/

install:
  - "SET PATH=C:\\Python27;C:\\Python27\\Scripts;%PATH%"
  - "SET TOX_TESTENV_PASSENV=HOME USERPROFILE HOMEPATH HOMEDRIVE"
  - "pip install -U tox twine wheel"

# Build the binary after tests
build: false

test_script:
  - tox -e py27,freeze

artifacts:
  - path: dist\shub.exe
  - path: dist\shub-$(APPVEYOR_REPO_TAG_NAME)-windows.zip

before_deploy:
  - 7z a dist\shub-%APPVEYOR_REPO_TAG_NAME%-windows.zip %APPVEYOR_BUILD_FOLDER%\dist\shub.exe

deploy:
  provider: GitHub
  # Should never be used as we'll have created a release before AppVeyor deploy
  # description: 'shub'
  auth_token:
    secure: mNA38grRkwGjw4zSUX1qA67eE6CRPjk97hRngZf19FuopBwbpPjOALBIlYZWKlDv
  artifact: dist\shub-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
  draft: true
  on:
    appveyor_repo_tag: true
